### PR TITLE
Verify indala64 checksums when reading

### PR DESCRIPTION
**Pull request by Aketzu**
I implemented simple checks for Indala checksums. By default I get 90% wrong reads for some reason and with this patch only about 10% wrong uid's.
Tested with keyfobs and readers I have around here.

### CODE REVIEW

**Comment by tonynaggs** [comment]
Moi moi

Thanks for the contribution.

There is one part I am not clear on, in the parity checking:
        if (response[i] >= 'a' && response[i] <= 'f')
            n = response[i] - 32;

It seems like the the second line should be either:
            response[i] = response[i] - 32; // convert to upper case
or
            n = response[i] - 'a' - 10;
(followed by an extra else).

Cheers,
Tony

**Comment by Aketzu** [comment]
That nibble to number conversion is copypasted from util.c:hextobinarray() with the difference that I don't want to modify response itself. (Yes, I think -32 is somewhat unclear. Should be fixed in both places.)

**Comment by tonynaggs** [comment]
I have pushed some minor tweaks, including adding a check for the strlen(response).
I don't have have any Indala tags to test with, so bug me if I've broken anything.

I'll nudge Adam to test, and to update the hex files. (My Windows builds all end up with a version string of 0.)

I'm not going to touch the hextobinarray() at the moment, as it is a little different and does the lower -> upper case conversion in place.

Cheers!

**Comment by AdamLaurie** [comment]
I've tested an Indala 64 TAG with the new code and it seems to work, which is nice! :) I can't commit HEX files at the moment as I have Q5 sniffing work in progress that needs to be finished, but that should happen shortly anyway. Thanks for the contribution.

**Pull request merged**
